language:
  java
jdk:
  - oraclejdk8

before_script:
  - pip install --user codecov
script:
  - ./gradlew clean build dist

after_success:
  - ./gradlew jacocoTestReport
  - codecov

install: echo "Installing Camel Spring ..."

before_deploy:
  - ls -al build/distributions

deploy:
  - provider: s3
    access_key_id: AKIAIW6HI5TNR23JK3UA
    secret_access_key: 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
    local_dir: build/distributions
    skip_cleanup: true
    on: &2
      repo: larryfang/camel-spring
    bucket: camelspring-bucket
    region: ap-southeast-2
  - provider: codedeploy
    access_key_id: AKIAIW6HI5TNR23JK3UA
    secret_access_key: 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
    bucket: camelspring-bucket
    key: camel-spring.zip
    bundle_type: zip
    application: SpringCamelDemo
    deployment_group: SpringCamelDemoGroup
    on: *2
    region: ap-southeast-2
